### ISSUE TITLE
Slider improvements

### ISSUE THREAD

**Issue by gillhofer** [Caleydo/org.caleydo.view.furby#10]
There should be two different kind of sliders. Horizontal and Vertical ones.
![image](https://f.cloud.github.com/assets/4135093/462404/00b20148-b4ac-11e2-9ede-4c4fa1215666.png)

_The other thing is_: 
If i change the slider value by moving the grey bar, my parent element thinks it gets dragged.
**Solution**:  There should be an easy accessible method for filtering those wrong dragging events. Something like: 

``` java
slider.isBarDragged(). 
```

Should be easy implemented through an additional boolean variable

**Comment by sgratzl** [comment]
1. why can't use use scrollbars instead of sliders. 
2. I can't get it why the parent element thinks that it wil be dragged. There are pick.isAnyDragging and pick.isDragging to check if any or itself called setIsDragging(true). Moreover I don't know why your parent gets the drag events as only the top most element should get the events -> you may have to increase the z-value of the slider

**Comment by gillhofer** [comment]
1) Visual consistency. Why using different objects?. If they are identical, where can i find these scrollbars, and how to use them?
2) TODO

**Comment by sgratzl** [comment]
part of e30450eb0cbe879b3f9d5428e2ffc8c6f536a089 just set isHorizontal(false) or create or own version of a GLSlider

**Comment by gillhofer** [comment]
Thank you very much!
