### ISSUE TITLE
Band splitting for bands that cannot be sorted otherwise

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.furby#15]

**Comment by gillhofer** [comment]
Implemented with https://github.com/sgratzl/caleydo-bicluster/commit/4e038e58b85e8dad4802a930a3c516e46d6c16be https://github.com/sgratzl/caleydo-bicluster/commit/d46424277b0bf536604652247c1e91d8f45d4d7e

I implemented this features for the dimension bands and I deactivated the splitting for record bands. 

Record bands usually are much thinner, and thus the splitted band must be very precisely positioned on top of the non splitted band. Otherwise it would happen that the user moves his mouse over a band ---> triggers the switch to the splitted band ---> now mouse is outside ---> triggers again the switch to the non splitted band. 

I couldn't find an acceptable solution for this rapid switching problem, so i deactivated the splitting of record bands.
