### ISSUE TITLE
Check out if approach also works for PCA/ICP/SVD

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.furby#22]

**Comment by gillhofer** [comment]
For PCA it kinda works. Since the visualisation is designed for BiClusters it needs a identical amount of columns in L and Z. 

If you use PCA, you get as many components as you have columns (or rows) in the source table. Because this vis is designed for BiClusters, where L and Z have the same amount of Columns, you need either 
- a quadratic source table, 
- or you omit components, 
- or you build two different visualisations. One for Rows, one for Columns, and you set L  (for Rows) or Z (for columns) values to 1 or a similar high value. The other table should then contain the calculated loading factors.  The vis will then show all records in the source data and depending of the PCA result the dimensions which have influence on the component. 

This leads to a decent representation where in every heatmap a different component is shown. With the corresponding sliders you can define minimum loading factors. So only the dimensions are shown which have (according to the set threshold) influence on the component. You will also get a band if a Dimension/Record is visible in 2 or more components.
