### ISSUE TITLE
Import Chemical Clusters as own data domains

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.furby#41]
as an alternative to import data directly via the BiCluster UI, it would be useful to have the Chemical Clusters either as a grouping within the X table or as an own data domain (simpler)

**Comment by sgratzl** [comment]
special clusters where no elements are matching, i.e. no bands, should automatically be hidden

**Comment by sgratzl** [comment]
> special clusters where no elements are matching, i.e. no bands, should automatically be hidden

@gillhofer  any idea how I could implement that?

**Comment by gillhofer** [comment]
Thats a bit tricky, because a cluster doesn't know about bands, and bands have no clue about clusters.

One possibility would be to alter or overwrite the calculateOverlap method in ClusterElement, and check if there is any overlap with another cluster. That should be quite fast, because the method is called anyways.

This method calculates the elements of bands by computing the intersection of this cluster with all other clusters. 
Create a boolean variable to store if there is no overlap with another cluster. Overwrite the setVisibility() method in  specialRecordClusterElement and the  specialChemicalClusterElement by using this boolean value. And call this method in cacluateOverlap().

**Comment by gillhofer** [comment]
An easier way should be to use the recordOverlapSize and dimensionOverlapSize variables (there are public available getter methods), which are set in the calculateOverlap method.

If those variables are zero, there is no overlap with other clusters and therefore no bands. --> You may need to overwrite the the setVisibility functions anyways.

**Comment by sgratzl** [comment]
this approach works more or less, another issue that I'm facing is that the cluster should be hidden if no _visible_ bands are there. i.e. if the opposite cluster is hidden, I don't need to render the cluster.

**Comment by gillhofer** [comment]
Maybe the simplest solution would be to store in the GLRootElement which cluster is hidden. To get and store this information just alter the listenTo(ClusterGetsHiddenEvent e) method in GLRootElement. The sender of this event should be the cluster which is getting hidden. 
//EDIT. There is a bug. The sender isn't set. Please alter the "private void hideThisCluster()" Method in ClusterElement and set the sender of the event. //

Then if you are checking the recordOverlapSize and dimensionOverlapSize variables, you could additionally ask the GLRootElement (variable "biclusterRoot" in every ClusterElement) whether this cluster is hidden and then treat it like there is no overlap.
To reach this goal you could create a public available method like "isClusterHidden(ClusterElement) in the GLRootElement".
